# Generated by Django 3.2.7 on 2021-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('admission_date', models.DateField()),
                ('got_discharge', models.BooleanField(default=False)),
                ('ward_number', models.IntegerField()),
                ('total_payment', models.IntegerField()),
            ],
        ),
    ]
