# Generated by Django 3.2.7 on 2021-09-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='disease',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
