# Generated by Django 3.2.7 on 2021-09-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_details_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('disease', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_for_appointment', models.DateField()),
            ],
        ),
    ]
